# Generated by Django 3.1.7 on 2021-03-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_cost', models.IntegerField()),
                ('product_type', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=100)),
            ],
        ),
    ]
